/**
 * Veterinary Clinic — 02 Index Creation
 *
 * Auto-generated by AppSpec v1.0.
 * Docker entrypoint: /docker-entrypoint-initdb.d/02-indexes.js
 *
 * Creates indexes from spec: explicit, unique, filterable, sortable, reference.
 * Deduplicates single-field indexes; try/catch prevents one failure from aborting all.
 */

const DB_NAME = "vet_clinic";
db = db.getSiblingDB(DB_NAME);

print(`[02-indexes] Creating indexes in ${DB_NAME}`);

// ── owners ──────────────────────────────────────



try {
  db.owners.createIndex(
    { "first_name": 1 },
    { name: "owners_first_name_filter" }
  );
} catch (e) { print(`  SKIP: owners.first_name filter — ${e.message}`); }
try {
  db.owners.createIndex(
    { "last_name": 1 },
    { name: "owners_last_name_filter" }
  );
} catch (e) { print(`  SKIP: owners.last_name filter — ${e.message}`); }
try {
  db.owners.createIndex(
    { "email": 1 },
    { name: "owners_email_filter" }
  );
} catch (e) { print(`  SKIP: owners.email filter — ${e.message}`); }

try {
  db.owners.createIndex(
    { "created_at": -1 },
    { name: "owners_created_at_sort" }
  );
} catch (e) { print(`  SKIP: owners.created_at sort — ${e.message}`); }



print(`  owners: indexes done`);

// ── patients ──────────────────────────────────────



try {
  db.patients.createIndex(
    { "name": 1 },
    { name: "patients_name_filter" }
  );
} catch (e) { print(`  SKIP: patients.name filter — ${e.message}`); }
try {
  db.patients.createIndex(
    { "species": 1 },
    { name: "patients_species_filter" }
  );
} catch (e) { print(`  SKIP: patients.species filter — ${e.message}`); }
try {
  db.patients.createIndex(
    { "breed": 1 },
    { name: "patients_breed_filter" }
  );
} catch (e) { print(`  SKIP: patients.breed filter — ${e.message}`); }
try {
  db.patients.createIndex(
    { "owner_id": 1 },
    { name: "patients_owner_id_filter" }
  );
} catch (e) { print(`  SKIP: patients.owner_id filter — ${e.message}`); }

try {
  db.patients.createIndex(
    { "date_of_birth": -1 },
    { name: "patients_date_of_birth_sort" }
  );
} catch (e) { print(`  SKIP: patients.date_of_birth sort — ${e.message}`); }
try {
  db.patients.createIndex(
    { "created_at": -1 },
    { name: "patients_created_at_sort" }
  );
} catch (e) { print(`  SKIP: patients.created_at sort — ${e.message}`); }



print(`  patients: indexes done`);

// ── appointments ──────────────────────────────────────



try {
  db.appointments.createIndex(
    { "patient_id": 1 },
    { name: "appointments_patient_id_filter" }
  );
} catch (e) { print(`  SKIP: appointments.patient_id filter — ${e.message}`); }
try {
  db.appointments.createIndex(
    { "owner_id": 1 },
    { name: "appointments_owner_id_filter" }
  );
} catch (e) { print(`  SKIP: appointments.owner_id filter — ${e.message}`); }
try {
  db.appointments.createIndex(
    { "appointment_date": 1 },
    { name: "appointments_appointment_date_filter" }
  );
} catch (e) { print(`  SKIP: appointments.appointment_date filter — ${e.message}`); }
try {
  db.appointments.createIndex(
    { "reason": 1 },
    { name: "appointments_reason_filter" }
  );
} catch (e) { print(`  SKIP: appointments.reason filter — ${e.message}`); }
try {
  db.appointments.createIndex(
    { "status": 1 },
    { name: "appointments_status_filter" }
  );
} catch (e) { print(`  SKIP: appointments.status filter — ${e.message}`); }

try {
  db.appointments.createIndex(
    { "created_at": -1 },
    { name: "appointments_created_at_sort" }
  );
} catch (e) { print(`  SKIP: appointments.created_at sort — ${e.message}`); }



print(`  appointments: indexes done`);

print("[02-indexes] Done.");
