/**
 * Veterinary Clinic — Aggregation Pipelines
 *
 * Auto-generated by AppSpec v1.0.
 * Derived from entity relationships (reference fields → $lookup).
 */

// ── patients: join related data ──

db.patients.aggregate([
  {
    $lookup: {
      from: "owners",
      localField: "owner_id",
      foreignField: "_id",
      as: "owner_details"
    }
  },
  {
    $unwind: {
      path: "$owner_details",
      preserveNullAndEmptyArrays: true
    }
  },
  { $limit: 50 }
]);

// ── appointments: join related data ──

db.appointments.aggregate([
  {
    $lookup: {
      from: "patients",
      localField: "patient_id",
      foreignField: "_id",
      as: "patient_details"
    }
  },
  {
    $unwind: {
      path: "$patient_details",
      preserveNullAndEmptyArrays: true
    }
  },
  {
    $lookup: {
      from: "owners",
      localField: "owner_id",
      foreignField: "_id",
      as: "owner_details"
    }
  },
  {
    $unwind: {
      path: "$owner_details",
      preserveNullAndEmptyArrays: true
    }
  },
  { $limit: 50 }
]);

