/**
 * Veterinary Clinic — MongoDB Indexes
 *
 * Auto-generated by AppSpec v1.0.
 * Run: mongosh < indexes.js
 */

// ── owners ──


try {
  db.owners.createIndex(
    { "first_name": 1 },
    { name: "owners_first_name_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.owners.createIndex(
    { "last_name": 1 },
    { name: "owners_last_name_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.owners.createIndex(
    { "email": 1 },
    { name: "owners_email_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }

try {
  db.owners.createIndex(
    { "created_at": -1 },
    { name: "owners_created_at_sort" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }


// ── patients ──


try {
  db.patients.createIndex(
    { "name": 1 },
    { name: "patients_name_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.patients.createIndex(
    { "species": 1 },
    { name: "patients_species_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.patients.createIndex(
    { "breed": 1 },
    { name: "patients_breed_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.patients.createIndex(
    { "owner_id": 1 },
    { name: "patients_owner_id_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }

try {
  db.patients.createIndex(
    { "date_of_birth": -1 },
    { name: "patients_date_of_birth_sort" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.patients.createIndex(
    { "created_at": -1 },
    { name: "patients_created_at_sort" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }


// ── appointments ──


try {
  db.appointments.createIndex(
    { "patient_id": 1 },
    { name: "appointments_patient_id_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.appointments.createIndex(
    { "owner_id": 1 },
    { name: "appointments_owner_id_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.appointments.createIndex(
    { "appointment_date": 1 },
    { name: "appointments_appointment_date_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.appointments.createIndex(
    { "reason": 1 },
    { name: "appointments_reason_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }
try {
  db.appointments.createIndex(
    { "status": 1 },
    { name: "appointments_status_filter" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }

try {
  db.appointments.createIndex(
    { "created_at": -1 },
    { name: "appointments_created_at_sort" }
  );
} catch (e) { print(`  SKIP: ${e.message}`); }


