/**
 * Veterinary Clinic — Seed Data
 *
 * Auto-generated by AppSpec v1.0.
 * Run: mongosh vet_clinic < seed.js
 *
 * Inserts demo documents per collection for development and testing.
 */

const DB_NAME = "vet_clinic";
print(`Seeding database: ${DB_NAME}`);


// ── Owner (owners) — 5 documents ──
try {
  const ownersResult = db.owners.insertMany([
    {
      id: "owner_1",
      first_name: "Alice",
      last_name: "Smith",
      email: "alice.smith@example.com",
      phone_number: "555-123-4567",
      address: "123 Oak Ave, Anytown, CA 90210",
      created_at: new Date("2024-01-10T09:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "owner_2",
      first_name: "Bob",
      last_name: "Johnson",
      email: "bob.johnson@example.com",
      phone_number: "555-234-5678",
      address: "456 Pine St, Otherville, NY 10001",
      created_at: new Date("2024-01-15T10:30:00Z"),
      updated_at: new Date()
    },
    {
      id: "owner_3",
      first_name: "Charlie",
      last_name: "Brown",
      email: "charlie.brown@example.com",
      phone_number: "555-345-6789",
      address: "789 Maple Rd, Somewhere, TX 75001",
      created_at: new Date("2024-02-01T11:45:00Z"),
      updated_at: new Date()
    },
    {
      id: "owner_4",
      first_name: "Diana",
      last_name: "Prince",
      email: "diana.prince@example.com",
      phone_number: "555-456-7890",
      address: "101 Elm Blvd, Metropolis, IL 60601",
      created_at: new Date("2024-02-20T13:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "owner_5",
      first_name: "Edward",
      last_name: "Clark",
      email: "edward.clark@example.com",
      phone_number: "555-567-8901",
      address: "222 Birch Ln, Gotham, NJ 07001",
      created_at: new Date("2024-03-05T14:15:00Z"),
      updated_at: new Date()
    }
  ]);
  print("  OK: owners — " + Object.values(ownersResult.insertedIds).length + " documents inserted");
} catch (e) {
  print("  SKIP: owners seed — " + e.message);
}

// ── Patient (patients) — 5 documents ──
try {
  const patientsResult = db.patients.insertMany([
    {
      id: "patient_1",
      name: "Buddy",
      species: "Dog",
      breed: "Golden Retriever",
      date_of_birth: new Date("2020-05-10T00:00:00Z"),
      owner_id: "owner_1",
      created_at: new Date("2024-01-10T09:15:00Z"),
      updated_at: new Date()
    },
    {
      id: "patient_2",
      name: "Whiskers",
      species: "Cat",
      breed: "Siamese",
      date_of_birth: new Date("2021-03-22T00:00:00Z"),
      owner_id: "owner_2",
      created_at: new Date("2024-01-15T10:45:00Z"),
      updated_at: new Date()
    },
    {
      id: "patient_3",
      name: "Tweety",
      species: "Bird",
      breed: "Canary",
      date_of_birth: new Date("2022-01-01T00:00:00Z"),
      owner_id: "owner_3",
      created_at: new Date("2024-02-01T12:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "patient_4",
      name: "Hoppy",
      species: "Rabbit",
      breed: "Dutch",
      date_of_birth: new Date("2023-07-15T00:00:00Z"),
      owner_id: "owner_4",
      created_at: new Date("2024-02-20T13:15:00Z"),
      updated_at: new Date()
    },
    {
      id: "patient_5",
      name: "Shadow",
      species: "Dog",
      breed: "German Shepherd",
      date_of_birth: new Date("2019-11-01T00:00:00Z"),
      owner_id: "owner_5",
      created_at: new Date("2024-03-05T14:30:00Z"),
      updated_at: new Date()
    }
  ]);
  print("  OK: patients — " + Object.values(patientsResult.insertedIds).length + " documents inserted");
} catch (e) {
  print("  SKIP: patients seed — " + e.message);
}

// ── Appointment (appointments) — 5 documents ──
try {
  const appointmentsResult = db.appointments.insertMany([
    {
      id: "appointment_1",
      patient_id: "patient_1",
      owner_id: "owner_1",
      appointment_date: new Date("2024-04-10T10:00:00Z"),
      reason: "Annual check-up and vaccinations",
      status: "scheduled",
      notes: "Client requested early morning slot. Buddy is due for rabies and distemper.",
      created_at: new Date("2024-03-25T15:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "appointment_2",
      patient_id: "patient_2",
      owner_id: "owner_2",
      appointment_date: new Date("2024-03-01T14:30:00Z"),
      reason: "Lethargy and loss of appetite",
      status: "completed",
      notes: "Diagnosed with mild gastroenteritis. Prescribed antibiotics and special diet. Whiskers is recovering well.",
      created_at: new Date("2024-02-28T09:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "appointment_3",
      patient_id: "patient_3",
      owner_id: "owner_3",
      appointment_date: new Date("2024-03-15T11:00:00Z"),
      reason: "Wing injury",
      status: "cancelled",
      notes: "Owner called to cancel, stated they found an avian specialist closer to home. No reschedule.",
      created_at: new Date("2024-03-10T16:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "appointment_4",
      patient_id: "patient_4",
      owner_id: "owner_4",
      appointment_date: new Date("2024-02-25T09:30:00Z"),
      reason: "Routine nail trim",
      status: "no_show",
      notes: "Client did not arrive for appointment. No call or email received. Attempted to reach by phone, no answer.",
      created_at: new Date("2024-02-20T10:00:00Z"),
      updated_at: new Date()
    },
    {
      id: "appointment_5",
      patient_id: "patient_5",
      owner_id: "owner_5",
      appointment_date: new Date("2024-04-20T16:00:00Z"),
      reason: "Follow-up for skin rash",
      status: "scheduled",
      notes: "Shadow's rash has improved, but owner wants a re-check. Advised to continue current medication.",
      created_at: new Date("2024-03-30T11:00:00Z"),
      updated_at: new Date()
    }
  ]);
  print("  OK: appointments — " + Object.values(appointmentsResult.insertedIds).length + " documents inserted");
} catch (e) {
  print("  SKIP: appointments seed — " + e.message);
}


print("Seeding complete.");
