/**
 * Veterinary Clinic — Database Setup
 *
 * Auto-generated by AppSpec v1.0.
 * Run: mongosh vet_clinic < setup.js
 */

const DB_NAME = "vet_clinic";

print(`Setting up database: ${DB_NAME}`);

// ── Create owners ──
if (!db.getCollectionNames().includes("owners")) {
  db.createCollection("owners");
}

// ── Create patients ──
if (!db.getCollectionNames().includes("patients")) {
  db.createCollection("patients");
}

// ── Create appointments ──
if (!db.getCollectionNames().includes("appointments")) {
  db.createCollection("appointments");
}


print("Setup complete.");
