/**
 * Veterinary Clinic — Mongoose Models
 *
 * Auto-generated by AppSpec v1.0.
 */

import mongoose, { Schema, Document } from "mongoose";

export interface IOwner extends Document {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string;
  address: string;
  created_at: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

const OwnerSchema = new Schema<IOwner>(
  {
    id: { type: String, required: true },
    first_name: { type: String, required: true },
    last_name: { type: String, required: true },
    email: { type: String, required: true },
    phone_number: { type: String, required: true },
    address: { type: String, required: true },
    created_at: { type: Date, required: true },
  },
  { timestamps: true }
);

export const Owner = mongoose.model<IOwner>("Owner", OwnerSchema);

export interface IPatient extends Document {
  id: string;
  name: string;
  species: string;
  breed: string;
  date_of_birth: Date;
  owner_id: mongoose.Types.ObjectId;
  created_at: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

const PatientSchema = new Schema<IPatient>(
  {
    id: { type: String, required: true },
    name: { type: String, required: true },
    species: { type: String, required: true },
    breed: { type: String, required: true },
    date_of_birth: { type: Date, required: true },
    owner_id: { type: Schema.Types.ObjectId, ref: "owners", required: true },
    created_at: { type: Date, required: true },
  },
  { timestamps: true }
);

export const Patient = mongoose.model<IPatient>("Patient", PatientSchema);

export interface IAppointment extends Document {
  id: string;
  patient_id: mongoose.Types.ObjectId;
  owner_id: mongoose.Types.ObjectId;
  appointment_date: Date;
  reason: string;
  status: string;
  notes: string;
  created_at: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

const AppointmentSchema = new Schema<IAppointment>(
  {
    id: { type: String, required: true },
    patient_id: { type: Schema.Types.ObjectId, ref: "patients", required: true },
    owner_id: { type: Schema.Types.ObjectId, ref: "owners", required: true },
    appointment_date: { type: Date, required: true },
    reason: { type: String, required: true },
    status: { type: String, required: true, enum: ["scheduled", "completed", "cancelled", "no_show"] },
    notes: { type: String, required: true },
    created_at: { type: Date, required: true },
  },
  { timestamps: true }
);

export const Appointment = mongoose.model<IAppointment>("Appointment", AppointmentSchema);

