/**
 * Veterinary Clinic — API Routes
 *
 * Auto-generated by AppSpec v1.0.
 */

import { Router, Request, Response } from "express";
import { Owner } from "./models";
import { Patient } from "./models";
import { Appointment } from "./models";

export const router = Router();

// ── Owner ──────────────────────────────────────────


router.get("/owners", async (_req: Request, res: Response) => {
  const items = await Owner.find().sort({ _id: -1 }).limit(50);
  res.json(items);
});

router.get("/owners/:id", async (req: Request, res: Response) => {
  const item = await Owner.findById(req.params.id);
  if (!item) return res.status(404).json({ error: "Owner not found" });
  res.json(item);
});

router.post("/owners", async (req: Request, res: Response) => {
  const item = await Owner.create(req.body);
  res.status(201).json(item);
});

router.put("/owners/:id", async (req: Request, res: Response) => {
  const item = await Owner.findByIdAndUpdate(req.params.id, req.body, { new: true });
  if (!item) return res.status(404).json({ error: "Owner not found" });
  res.json(item);
});

router.delete("/owners/:id", async (req: Request, res: Response) => {
  const result = await Owner.findByIdAndDelete(req.params.id);
  if (!result) return res.status(404).json({ error: "Owner not found" });
  res.json({ ok: true });
});

// ── Patient ──────────────────────────────────────────


router.get("/patients", async (_req: Request, res: Response) => {
  const items = await Patient.find().sort({ _id: -1 }).limit(50);
  res.json(items);
});

router.get("/patients/:id", async (req: Request, res: Response) => {
  const item = await Patient.findById(req.params.id);
  if (!item) return res.status(404).json({ error: "Patient not found" });
  res.json(item);
});

router.post("/patients", async (req: Request, res: Response) => {
  const item = await Patient.create(req.body);
  res.status(201).json(item);
});

router.put("/patients/:id", async (req: Request, res: Response) => {
  const item = await Patient.findByIdAndUpdate(req.params.id, req.body, { new: true });
  if (!item) return res.status(404).json({ error: "Patient not found" });
  res.json(item);
});

router.delete("/patients/:id", async (req: Request, res: Response) => {
  const result = await Patient.findByIdAndDelete(req.params.id);
  if (!result) return res.status(404).json({ error: "Patient not found" });
  res.json({ ok: true });
});

// ── Appointment ──────────────────────────────────────────


router.get("/appointments", async (_req: Request, res: Response) => {
  const items = await Appointment.find().sort({ _id: -1 }).limit(50);
  res.json(items);
});

router.get("/appointments/:id", async (req: Request, res: Response) => {
  const item = await Appointment.findById(req.params.id);
  if (!item) return res.status(404).json({ error: "Appointment not found" });
  res.json(item);
});

router.post("/appointments", async (req: Request, res: Response) => {
  const item = await Appointment.create(req.body);
  res.status(201).json(item);
});

router.put("/appointments/:id", async (req: Request, res: Response) => {
  const item = await Appointment.findByIdAndUpdate(req.params.id, req.body, { new: true });
  if (!item) return res.status(404).json({ error: "Appointment not found" });
  res.json(item);
});

router.delete("/appointments/:id", async (req: Request, res: Response) => {
  const result = await Appointment.findByIdAndDelete(req.params.id);
  if (!result) return res.status(404).json({ error: "Appointment not found" });
  res.json({ ok: true });
});

