/**
 * Veterinary Clinic — Express Server
 *
 * Auto-generated by AppSpec v1.0.
 */

import express from "express";
import cors from "cors";
import mongoose from "mongoose";
import path from "path";
import { router } from "./routes";

const app = express();
const PORT = process.env.PORT || 8000;
const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/vet_clinic";

app.use(cors());
app.use(express.json());
app.use("/api", router);

app.get("/", (_req, res) => {
  res.json({
    app: "Veterinary Clinic",
    slug: "vet-clinic",
    health: "/health",
    api: "/api",
    ux: "/ux",
  });
});

app.get("/health", async (_req, res) => {
  const dbStatus = mongoose.connection.readyState === 1 ? "connected" : "unavailable";
  res.json({ status: "healthy", app: "vet-clinic", database: dbStatus });
});

app.get("/ux", (_req, res) => {
  res.sendFile(path.join(__dirname, "..", "static", "index.html"), (err) => {
    if (err) res.redirect("/");
  });
});

async function start() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB");
  app.listen(PORT, () => console.log(`Veterinary Clinic running on port ${PORT}`));
}

start().catch(console.error);
