"""Scaffold a new appspec/ folder with a minimal starter spec."""

from __future__ import annotations

from pathlib import Path

from appspec.compiler import compile_to_folder


def init_folder(target_dir: Path, app_name: str = "My App") -> dict[str, Path]:
    """Scaffold a new appspec/ folder with a minimal starter spec."""
    from appspec.models import (
        AppSpec,
        AuthSpec,
        CrudOperation,
        DataField,
        Endpoint,
        EntitySpec,
        FieldType,
        HttpMethod,
        UISpec,
    )

    slug = app_name.lower().replace(" ", "-")
    slug = "".join(c for c in slug if c.isalnum() or c == "-")

    spec = AppSpec(
        app_name=app_name,
        slug=slug,
        description=f"{app_name} — generated by AppSpec",
        auth=AuthSpec(enabled=False),
        entities=[
            EntitySpec(
                name="Item",
                collection="items",
                description="A generic item",
                fields=[
                    DataField(name="name", type=FieldType.STRING, required=True),
                    DataField(
                        name="status",
                        type=FieldType.ENUM,
                        enum_values=["active", "archived"],
                        is_filterable=True,
                    ),
                    DataField(name="created_at", type=FieldType.DATETIME, is_sortable=True),
                ],
            )
        ],
        endpoints=[
            Endpoint(method=HttpMethod.GET, path="/items", entity="Item", operation=CrudOperation.LIST),
            Endpoint(method=HttpMethod.GET, path="/items/{id}", entity="Item", operation=CrudOperation.GET),
            Endpoint(method=HttpMethod.POST, path="/items", entity="Item", operation=CrudOperation.CREATE),
            Endpoint(method=HttpMethod.PUT, path="/items/{id}", entity="Item", operation=CrudOperation.UPDATE),
            Endpoint(method=HttpMethod.DELETE, path="/items/{id}", entity="Item", operation=CrudOperation.DELETE),
        ],
        ui=UISpec(framework="react"),
    )

    appspec_dir = target_dir / "appspec"
    return compile_to_folder(spec, appspec_dir)
