/**
 * Veterinary Clinic — 00 Collection Setup
 *
 * Auto-generated by AppSpec v1.0.
 * Docker entrypoint: /docker-entrypoint-initdb.d/00-setup.js
 */

const DB_NAME = "vet_clinic";
db = db.getSiblingDB(DB_NAME);

print(`[00-setup] Creating collections in ${DB_NAME}`);

// owners
if (!db.getCollectionNames().includes("owners")) {
  db.createCollection("owners");
  print(`  Created collection: owners`);
} else {
  print(`  Collection owners already exists, skipping.`);
}

// patients
if (!db.getCollectionNames().includes("patients")) {
  db.createCollection("patients");
  print(`  Created collection: patients`);
} else {
  print(`  Collection patients already exists, skipping.`);
}

// appointments
if (!db.getCollectionNames().includes("appointments")) {
  db.createCollection("appointments");
  print(`  Created collection: appointments`);
} else {
  print(`  Collection appointments already exists, skipping.`);
}

print("[00-setup] Done.");
