"""Veterinary Clinic — Database Connection

Auto-generated by AppSpec v1.0.
"""

import os

from motor.motor_asyncio import AsyncIOMotorClient

_client: AsyncIOMotorClient | None = None
_db = None


async def connect_db():
    global _client, _db
    uri = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
    db_name = os.getenv("MONGODB_DB", "vet_clinic")
    _client = AsyncIOMotorClient(uri)
    _db = _client[db_name]


async def close_db():
    global _client
    if _client:
        _client.close()


def get_db():
    if _db is None:
        raise RuntimeError("Database not connected. Call connect_db() first.")
    return _db
