"""Veterinary Clinic — FastAPI Application

Auto-generated by AppSpec v1.0.
"""

import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, RedirectResponse

from database import connect_db, close_db
from routes import router


@asynccontextmanager
async def lifespan(app: FastAPI):
    await connect_db()
    yield
    await close_db()


app = FastAPI(
    title="Veterinary Clinic",
    description="A comprehensive application for managing pet owners, their pets (patients), and all associated appointments within a veterinary clinic.",
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/api")


@app.get("/")
async def root():
    return {
        "app": "Veterinary Clinic",
        "slug": "vet-clinic",
        "docs": "/docs",
        "health": "/health",
        "api": "/api",
        "ux": "/ux",
    }


@app.get("/health")
async def health():
    from database import get_db
    try:
        db = get_db()
        await db.command("ping")
        db_status = "connected"
    except Exception:
        db_status = "unavailable"
    return {"status": "healthy", "app": "vet-clinic", "database": db_status}


_static_dir = Path(__file__).parent / "static"


@app.get("/ux")
async def ux():
    html = _static_dir / "index.html"
    if html.exists():
        return FileResponse(html, media_type="text/html")
    return RedirectResponse("/docs")
