"""Veterinary Clinic — Pydantic Models

Auto-generated by AppSpec v1.0.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class OwnerCreate(BaseModel):
    """Create schema for Owner."""
    id: str = Field(..., description="Unique identifier for the owner.")
    first_name: str = Field(..., description="The first name of the pet owner.")
    last_name: str = Field(..., description="The last name of the pet owner.")
    email: str = Field(..., description="The email address of the pet owner, used for communication.")
    phone_number: str = Field(..., description="The primary phone number of the pet owner.")
    address: str = Field(..., description="The physical address of the pet owner.")
    created_at: datetime = Field(..., description="Timestamp when the owner record was created.")


class OwnerResponse(OwnerCreate):
    """Response schema for Owner."""
    id: str = Field(..., alias="_id")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"populate_by_name": True}


class PatientCreate(BaseModel):
    """Create schema for Patient."""
    id: str = Field(..., description="Unique identifier for the patient (pet).")
    name: str = Field(..., description="The name of the pet.")
    species: str = Field(..., description="The species of the pet (e.g., Dog, Cat, Bird).")
    breed: str = Field(..., description="The breed of the pet.")
    date_of_birth: datetime = Field(..., description="The birth date of the pet.")
    owner_id: str = Field(..., description="Reference to the owner of this pet.")
    created_at: datetime = Field(..., description="Timestamp when the patient record was created.")


class PatientResponse(PatientCreate):
    """Response schema for Patient."""
    id: str = Field(..., alias="_id")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"populate_by_name": True}


class AppointmentCreate(BaseModel):
    """Create schema for Appointment."""
    id: str = Field(..., description="Unique identifier for the appointment.")
    patient_id: str = Field(..., description="Reference to the patient (pet) for this appointment.")
    owner_id: str = Field(..., description="Reference to the owner associated with this appointment.")
    appointment_date: datetime = Field(..., description="The date and time of the appointment.")
    reason: str = Field(..., description="The reason for the appointment (e.g., check-up, vaccination, emergency).")
    status: str = Field(..., description="The current status of the appointment.")
    notes: str = Field(..., description="Any additional notes or observations for the appointment.")
    created_at: datetime = Field(..., description="Timestamp when the appointment record was created.")


class AppointmentResponse(AppointmentCreate):
    """Response schema for Appointment."""
    id: str = Field(..., alias="_id")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"populate_by_name": True}


