"""Veterinary Clinic — API Routes

Auto-generated by AppSpec v1.0.
"""

from datetime import datetime

from bson import ObjectId
from fastapi import APIRouter, HTTPException, Query

from database import get_db
from models import (
    OwnerCreate,
    OwnerResponse,
    PatientCreate,
    PatientResponse,
    AppointmentCreate,
    AppointmentResponse,
)

router = APIRouter()


def _oid(id_str: str) -> ObjectId:
    try:
        return ObjectId(id_str)
    except Exception:
        raise HTTPException(400, "Invalid ID format")


def _doc_to_response(doc: dict) -> dict:
    if not doc:
        return doc
    for key, value in doc.items():
        if isinstance(value, ObjectId):
            doc[key] = str(value)
    return doc


# ── Owner ──────────────────────────────────────────


@router.get("/owners", response_model=list[OwnerResponse])
async def list_owners(skip: int = Query(0, ge=0), limit: int = Query(50, ge=1, le=200)):
    db = get_db()
    cursor = db.owners.find().skip(skip).limit(limit).sort("_id", -1)
    return [_doc_to_response(doc) async for doc in cursor]

@router.get("/owners/{item_id}", response_model=OwnerResponse)
async def get_owners_by_id(item_id: str):
    db = get_db()
    doc = await db.owners.find_one({"_id": _oid(item_id)})
    if not doc:
        raise HTTPException(404, "Owner not found")
    return _doc_to_response(doc)

@router.post("/owners", response_model=OwnerResponse, status_code=201)
async def create_owners(data: OwnerCreate):
    db = get_db()
    doc = data.model_dump()
    doc["created_at"] = datetime.utcnow()
    doc["updated_at"] = doc["created_at"]
    result = await db.owners.insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    return doc

@router.put("/owners/{item_id}", response_model=OwnerResponse)
async def update_owners(item_id: str, data: OwnerCreate):
    db = get_db()
    update = {"$set": {**data.model_dump(), "updated_at": datetime.utcnow()}}
    result = await db.owners.find_one_and_update(
        {"_id": _oid(item_id)}, update, return_document=True
    )
    if not result:
        raise HTTPException(404, "Owner not found")
    return _doc_to_response(result)

@router.delete("/owners/{item_id}")
async def delete_owners(item_id: str):
    db = get_db()
    result = await db.owners.delete_one({"_id": _oid(item_id)})
    if result.deleted_count == 0:
        raise HTTPException(404, "Owner not found")
    return {"ok": True}

# ── Patient ──────────────────────────────────────────


@router.get("/patients", response_model=list[PatientResponse])
async def list_patients(skip: int = Query(0, ge=0), limit: int = Query(50, ge=1, le=200)):
    db = get_db()
    cursor = db.patients.find().skip(skip).limit(limit).sort("_id", -1)
    return [_doc_to_response(doc) async for doc in cursor]

@router.get("/patients/{item_id}", response_model=PatientResponse)
async def get_patients_by_id(item_id: str):
    db = get_db()
    doc = await db.patients.find_one({"_id": _oid(item_id)})
    if not doc:
        raise HTTPException(404, "Patient not found")
    return _doc_to_response(doc)

@router.post("/patients", response_model=PatientResponse, status_code=201)
async def create_patients(data: PatientCreate):
    db = get_db()
    doc = data.model_dump()
    doc["created_at"] = datetime.utcnow()
    doc["updated_at"] = doc["created_at"]
    result = await db.patients.insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    return doc

@router.put("/patients/{item_id}", response_model=PatientResponse)
async def update_patients(item_id: str, data: PatientCreate):
    db = get_db()
    update = {"$set": {**data.model_dump(), "updated_at": datetime.utcnow()}}
    result = await db.patients.find_one_and_update(
        {"_id": _oid(item_id)}, update, return_document=True
    )
    if not result:
        raise HTTPException(404, "Patient not found")
    return _doc_to_response(result)

@router.delete("/patients/{item_id}")
async def delete_patients(item_id: str):
    db = get_db()
    result = await db.patients.delete_one({"_id": _oid(item_id)})
    if result.deleted_count == 0:
        raise HTTPException(404, "Patient not found")
    return {"ok": True}

# ── Appointment ──────────────────────────────────────────


@router.get("/appointments", response_model=list[AppointmentResponse])
async def list_appointments(skip: int = Query(0, ge=0), limit: int = Query(50, ge=1, le=200)):
    db = get_db()
    cursor = db.appointments.find().skip(skip).limit(limit).sort("_id", -1)
    return [_doc_to_response(doc) async for doc in cursor]

@router.get("/appointments/{item_id}", response_model=AppointmentResponse)
async def get_appointments_by_id(item_id: str):
    db = get_db()
    doc = await db.appointments.find_one({"_id": _oid(item_id)})
    if not doc:
        raise HTTPException(404, "Appointment not found")
    return _doc_to_response(doc)

@router.post("/appointments", response_model=AppointmentResponse, status_code=201)
async def create_appointments(data: AppointmentCreate):
    db = get_db()
    doc = data.model_dump()
    doc["created_at"] = datetime.utcnow()
    doc["updated_at"] = doc["created_at"]
    result = await db.appointments.insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    return doc

@router.put("/appointments/{item_id}", response_model=AppointmentResponse)
async def update_appointments(item_id: str, data: AppointmentCreate):
    db = get_db()
    update = {"$set": {**data.model_dump(), "updated_at": datetime.utcnow()}}
    result = await db.appointments.find_one_and_update(
        {"_id": _oid(item_id)}, update, return_document=True
    )
    if not result:
        raise HTTPException(404, "Appointment not found")
    return _doc_to_response(result)

@router.delete("/appointments/{item_id}")
async def delete_appointments(item_id: str):
    db = get_db()
    result = await db.appointments.delete_one({"_id": _oid(item_id)})
    if result.deleted_count == 0:
        raise HTTPException(404, "Appointment not found")
    return {"ok": True}

